[package]
name = "btree-slab"
version = "0.1.1"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["data-structures"]
keywords = ["btree", "map", "set", "slab"]
description = "A memory compact Slab-based B-tree implementation"
repository = "https://github.com/timothee-haudebourg/local-btree"
documentation = "https://docs.rs/local-btree"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
default = ["std-slab", "dot"]
dot = []
std-slab = ["slab", "cc-traits/slab"]

[dependencies]
staticvec = "^0.10"
cc-traits = { path = "../../traits/cc-traits", features = ["nightly"] }
slab = { version = "^0.4", optional = true }

[dev-dependencies]
rand = { version = "^0.7", features = ["small_rng"] }
