[package]
name = "local-btree"
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["dot", "slab"]
dot = []

[dependencies]
staticvec = "^0.10"
slab = { version = "^0.4", optional = true }

[dev-dependencies]
rand = { version = "^0.7", features = ["small_rng"] }
