[package]
name = "local-btree"
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["data-structures"]
keywords = ["btree", "map", "set", "local"]
description = "A memory compact B-tree implementation"
repository = "https://github.com/timothee-haudebourg/local-btree"
documentation = "https://docs.rs/local-btree"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
default = ["dot", "slab"]
dot = []

[dependencies]
staticvec = "^0.10"
slab = { version = "^0.4", optional = true }

[dev-dependencies]
rand = { version = "^0.7", features = ["small_rng"] }
