[package]
name = "linear-btree"
version = "0.1.0"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["dot"]
dot = []

[dependencies]
staticvec = "^0.10.4"
slab = "*"

[dev-dependencies]
rand = { version = "^0.7", features = ["small_rng"] }
